services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/tmp
    environment:
      - GIN_MODE=debug
    networks:
      - suispicious-network
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true # Windows things
      - WATCHPACK_POLLING=true # Windows things
    networks:
      - suispicious-network
    depends_on:
      - server
    restart: unless-stopped

networks:
  suispicious-network:
    driver: bridge
