name: Deploy SUI Move Package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SUI CLI
        uses: baptiste0928/cargo-install@v3
        with:
          crate: sui
          git: https://github.com/MystenLabs/sui.git
          branch: testnet

      - name: Load key from secrets
        env:
          SUI_PRIVATE: ${{ secrets.SUI_PRIVATE }}
        run: |
          sui keytool --keystore-path ./.github/sui_config/sui.keystore import --alias "cicd" "${SUI_PRIVATE}" ed25519
      
      - name: Check gas
        run: |
          sui client --client.config ./.github/sui_config/sui_client.yaml gas

      - name: Build Move package
        run: sui move build -p ./move

      - name: Publish Move package
        run: |
          sui client --client.config ./.github/sui_config/sui_client.yaml publish ./move